name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code to VM
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          echo "ğŸ“ Ensuring app directory exists"
          mkdir -p /var/www

          echo "ğŸ“ Changing to app directory"
          cd /var/www/git-act || exit 1

      - name: Mark directory as safe for Git
        run: git config --global --add safe.directory /var/www/git-act


          echo "ğŸ“¥ Pulling latest code"
          git pull origin main

          echo "ğŸ“‚ Copying .env to /mnt/www"
          echo "$SUDO_PASSWORD" | sudo -S cp -pv .env /mnt/www/.env

          echo "ğŸ“¦ Installing dependencies"
          npm install

          echo "ğŸš€ Restarting app"
          pm2 start app.js --name "titles-server" --update-env -f || pm2 restart titles-server --update-env -f
